### PR TITLE
Add client.WithAPIVersionNegotiation() option for Docker client

### PR DESCRIPTION
**Pull request by k311093**
This makes Cloud Orchestrator possible to connect to docker servie with older version than docker client library.

### CODE REVIEW

**Review by ikicha — APPROVED** [review]

**Comment by 0405ysj** [comment]
Can we get rid of code around calculating docker API version in `scripts/docker/run.sh`?

**Review by 0405ysj — APPROVED** [review]

**Comment by k311093** [comment]
> Can we get rid of code around calculating docker API version in `scripts/docker/run.sh`?

I think so, it might do similar things at `scripts/docker/run.sh`. I tried just running cloud_orchestrator with configuration and succeeded to run with older docker version without additional environments.

**Comment by 0405ysj** [comment]
> I think so, it might do similar things at scripts/docker/run.sh

Then, why don't we cleanup that code with applying this? BTW, I'm okay to cleaning it up in following PR.

**Comment by k311093** [comment]
> > I think so, it might do similar things at scripts/docker/run.sh
> 
> Then, why don't we cleanup that code with applying this? BTW, I'm okay to cleaning it up in following PR.

Added commit for removing docker version related logic for script/docker/run.sh

**Review by jemoreira — APPROVED** [review]

**Pull request merged**
