### PR TITLE
Introduce url query account manager.

### PR DESCRIPTION
**Pull request by denniscy1993**
- URLQueryAccountManager gets the account username from a URL query parameter: `?user=<username>`.

Tests:
- `curl -k -d '{}' --request POST http://localhost:8080/v1/zones/local/hosts?user=<username>`
- `curl -k --request GET http://localhost:8080/v1/zones/local/hosts?user=<username>`
- `curl -k -d '{}' --request DELETE http://localhost:8080/v1/zones/local/hosts/<host_name>?user=<username>`

### CODE REVIEW

**Review by ser-io — APPROVED** [review]

**Comment by 0405ysj** [comment]
What's the purpose for introducing a new AM, despite of existence of `HttpBasicAccountManager`?

**Comment by denniscy1993** [comment]
> What's the purpose for introducing a new AM, despite of existence of `HttpBasicAccountManager`?

The motivation is to prevent from overengineering on top of http basic auth, so we are trying to replace `HttpBasicAccountManager` by this new `URLQueryAccountManager`. More details at b/340969490#comment1.

**Review by 0405ysj — APPROVED** [review]
The code itself looks good to me, but I think it's better to submit after checking if URLQueryAccountManager really needs.

**Comment by 0405ysj** [comment]
I think it's okay to submit.

**Comment by denniscy1993** [comment]
Closing this PR according to the discussion at b/340969490. Using url query may not be suitable for interacting with CO via a web page.

**Pull request closed without merging**
